import esbuild from "esbuild";
import process from "process";
import path from "path";
import fs from "fs";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Jhua Homepage Plugin - 个人生活工作学习中控台
*/
`;

const prod = (process.argv[2] === "production");

// 插件安装目录（Obsidian 从这里加载插件）
// WSL 环境：用 /mnt/d/ 路径，esbuild 在 WSL 内运行
const PLUGIN_DIR = "/mnt/d/Syncthing-Kopia/JHUA-Obsidian-Vault/.obsidian/plugins/jhua-hpage";

// 复制 static 文件到插件目录
function copyStaticFiles() {
  const files = ["styles.css", "manifest.json", "versions.json"];
  for (const f of files) {
    const src = path.resolve(f);
    const dest = path.join(PLUGIN_DIR, f);
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dest);
    }
  }
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/closebrackets",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/comment",
    "@codemirror/fold",
    "@codemirror/gutter",
    "@codemirror/highlight",
    "@codemirror/history",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/matchbrackets",
    "@codemirror/panel",
    "@codemirror/rangeset",
    "@codemirror/rectangular-selection",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/stream-parser",
    "@codemirror/text",
    "@codemirror/tooltip",
    "@codemirror/view",
    ...builtins
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(PLUGIN_DIR, "main.js"),
});

if (prod) {
  await context.rebuild();
  // 构建完成后自动复制 static 文件
  copyStaticFiles();
  console.log("✅ Static files copied to plugin dir:", PLUGIN_DIR);
  process.exit(0);
} else {
  // dev 模式也先复制一次
  copyStaticFiles();
  await context.watch();
}
