/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Jhua Homepage Plugin - 个人生活工作学习中控台
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JhuaHPagePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  todoCachePath: "VaultSources/\u4E3B\u9875\u6570\u636E/todos.json",
  categories: [
    {
      id: "cat-1",
      name: "Obsidian",
      icon: "\u{1FA9B}",
      color: "#5B93D5",
      items: [
        { id: "item-1", name: "\u8BBE\u7F6E", path: "obsidian://show-settings", icon: "\u2699\uFE0F" },
        { id: "item-2", name: "\u4ECA\u65E5\u65E5\u8BB0", path: "obsidian://daily-note", icon: "\u{1F4C5}" }
      ]
    },
    {
      id: "cat-2",
      name: "\u4E2A\u4EBA",
      icon: "\u{1F60F}",
      color: "#E07B53",
      items: [
        { id: "item-3", name: "\u4E3B\u9875", path: "01-\u9886\u57DF\uFF08Areas\uFF09/00-\u65E5\u5E38\u8BB0\u5F55/00-\u4E3B\u9875/\u4E3B\u9875.md", icon: "\u{1F3E0}" }
      ]
    }
  ],
  bannerImage: "VaultSources/pasted_pics/\u3010\u54F2\u98CE\u58C1\u7EB8\u3011\u5929\u7A7A\u8349\u5730-\u5C11\u5E74\u5954\u8DD1.png",
  bannerTitle: "\u6B22\u8FCE\u56DE\u6765",
  countdowns: [],
  projectCreateUri: "",
  unorganizedCreateUri: "",
  dailyNoteTemplate: "templates/11-\u65E5\u8BB0\u6A21\u677F.md"
};
var TodoManager = class {
  constructor(app, cachePath) {
    this.app = app;
    this.cachePath = cachePath;
    this.cache = {
      version: "1.0",
      todos: [],
      completedTodos: [],
      settings: {
        showCompleted: false,
        sortBy: "priority"
      }
    };
  }
  async load() {
    try {
      const file = this.app.vault.getAbstractFileByPath(this.cachePath);
      if (file instanceof import_obsidian.TFile) {
        const content = await this.app.vault.read(file);
        this.cache = JSON.parse(content);
      }
    } catch (e) {
      await this.save();
    }
  }
  async save() {
    try {
      const dirPath = this.cachePath.substring(0, this.cachePath.lastIndexOf("/"));
      if (!this.app.vault.getAbstractFileByPath(dirPath)) {
        await this.app.vault.createFolder(dirPath);
      }
      const file = this.app.vault.getAbstractFileByPath(this.cachePath);
      const content = JSON.stringify(this.cache, null, 2);
      if (file instanceof import_obsidian.TFile) {
        await this.app.vault.modify(file, content);
      } else {
        await this.app.vault.create(this.cachePath, content);
      }
    } catch (e) {
      console.error("\u4FDD\u5B58\u5F85\u529E\u7F13\u5B58\u5931\u8D25:", e);
    }
  }
  getTodos() {
    return this.cache.todos;
  }
  getCompletedTodos() {
    return this.cache.completedTodos;
  }
  async addTodo(content, priority = "medium", dueDate, tags) {
    const todo = {
      id: `todo-${Date.now()}`,
      content,
      completed: false,
      priority,
      dueDate,
      tags,
      createdAt: (/* @__PURE__ */ new Date()).toISOString()
    };
    this.cache.todos.push(todo);
    await this.save();
    return todo;
  }
  async toggleTodo(id) {
    const todo = this.cache.todos.find((t) => t.id === id);
    if (todo) {
      todo.completed = !todo.completed;
      if (todo.dueDate) {
        await this.syncTodoStatusToDailyNote(todo.dueDate, todo.content, todo.completed);
      }
      await this.save();
    }
  }
  async deleteTodo(id) {
    this.cache.todos = this.cache.todos.filter((t) => t.id !== id);
    this.cache.completedTodos = this.cache.completedTodos.filter((t) => t.id !== id);
    await this.save();
  }
  async getWeeklyTodosFromDailyNotes() {
    const weeklyTodos = [];
    const weekDates = this.getWeekDates();
    for (const dateStr of weekDates) {
      const dailyNotePath = this.getDailyNotePath(dateStr);
      const file = this.app.vault.getAbstractFileByPath(dailyNotePath);
      if (file instanceof import_obsidian.TFile) {
        const content = await this.app.vault.read(file);
        const todos = this.extractTodosFromContent(content, dateStr);
        weeklyTodos.push(...todos);
      }
    }
    return weeklyTodos;
  }
  getWeekDates() {
    const dates = [];
    const today = /* @__PURE__ */ new Date();
    const dayOfWeek = today.getDay();
    const monday = new Date(today);
    const diff = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
    monday.setDate(today.getDate() + diff);
    for (let i = 0; i < 7; i++) {
      const date = new Date(monday);
      date.setDate(monday.getDate() + i);
      const dateStr = date.toISOString().split("T")[0];
      dates.push(dateStr);
    }
    return dates;
  }
  extractTodosFromContent(content, dateStr) {
    const todos = [];
    const lines = content.split("\n");
    let inTasksSection = false;
    for (const line of lines) {
      if (line.match(/^#\s*📖\s*Tasks/i)) {
        inTasksSection = true;
        continue;
      }
      if (inTasksSection && line.match(/^#/)) {
        break;
      }
      if (inTasksSection) {
        const match = line.match(/^- \[([ x])\] (.+)$/);
        if (match) {
          const completed = match[1] === "x";
          const todoContent = match[2].trim();
          const existsInCache = this.cache.todos.some(
            (t) => t.content === todoContent && t.dueDate === dateStr
          );
          if (!existsInCache && todoContent) {
            todos.push({
              id: `daily-${dateStr}-${Date.now()}-${Math.random()}`,
              content: todoContent,
              completed,
              priority: "medium",
              dueDate: dateStr,
              createdAt: (/* @__PURE__ */ new Date()).toISOString()
            });
          }
        }
      }
    }
    return todos;
  }
  async syncTodoStatusToDailyNote(dateStr, content, completed) {
    const dailyNotePath = this.getDailyNotePath(dateStr);
    try {
      let file = this.app.vault.getAbstractFileByPath(dailyNotePath);
      if (!(file instanceof import_obsidian.TFile)) {
        await this.createDailyNoteWithURI(dateStr);
        await new Promise((resolve) => setTimeout(resolve, 1e3));
        file = this.app.vault.getAbstractFileByPath(dailyNotePath);
      }
      if (file instanceof import_obsidian.TFile) {
        let fileContent = await this.app.vault.read(file);
        const checkbox = completed ? "- [x]" : "- [ ]";
        const escapedContent = content.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        const regex = new RegExp(`(- \\[([ x])\\] ${escapedContent})`, "g");
        fileContent = fileContent.replace(regex, `${checkbox} ${content}`);
        await this.app.vault.modify(file, fileContent);
      }
    } catch (e) {
      console.error("\u540C\u6B65\u5F85\u529E\u72B6\u6001\u5230\u65E5\u8BB0\u5931\u8D25:", e);
    }
  }
  async createDailyNoteWithURI(dateStr) {
    const uri = `obsidian://adv-uri?vault=JHUA-Obsidian-Vault&commandid=daily-notes`;
    window.open(uri, "_blank");
  }
  getDailyNotePath(dateStr) {
    const [year, month] = dateStr.split("-");
    return `01-\u9886\u57DF\uFF08Areas\uFF09/00-\u65E5\u5E38\u8BB0\u5F55/02-\u65E5\u8BB0/${year}/${year}-${month}/${dateStr}.md`;
  }
};
var VIEW_TYPE_HOMEPAGE = "jhua-hpage-view";
var HomepageView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.refreshInterval = null;
    this.projectSortState = { column: "ddl", direction: "asc" };
    this.plugin = plugin;
    this.todoManager = new TodoManager(this.app, plugin.settings.todoCachePath);
  }
  getViewType() {
    return VIEW_TYPE_HOMEPAGE;
  }
  getDisplayText() {
    return "\u4E3B\u9875";
  }
  getIcon() {
    return "home";
  }
  async onOpen() {
    await this.todoManager.load();
    await this.render();
    this.refreshInterval = window.setInterval(() => {
      this.updateDateTime();
    }, 6e4);
  }
  onClose() {
    if (this.refreshInterval) {
      window.clearInterval(this.refreshInterval);
    }
    return Promise.resolve();
  }
  async render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("jhua-hpage-container");
    this.renderBanner(container);
    this.renderNavigation(container);
    this.renderProjectTracking(container);
    const twoColumnContainer = container.createDiv({ cls: "jhua-two-column" });
    const leftColumn = twoColumnContainer.createDiv({ cls: "jhua-column jhua-column-left" });
    const rightColumn = twoColumnContainer.createDiv({ cls: "jhua-column jhua-column-right" });
    await this.renderTodoList(leftColumn);
    this.renderUnorganizedFiles(rightColumn);
    this.renderRecentFiles(container);
  }
  renderBanner(container) {
    const banner = container.createDiv({ cls: "jhua-banner" });
    const bgPath = this.plugin.settings.bannerImage;
    if (bgPath) {
      const bgFile = this.app.vault.getAbstractFileByPath(bgPath);
      if (bgFile instanceof import_obsidian.TFile) {
        const resourcePath = this.app.vault.getResourcePath(bgFile);
        banner.style.backgroundImage = `url('${resourcePath}')`;
        banner.addClass("jhua-banner-with-bg");
      }
    }
    const content = banner.createDiv({ cls: "jhua-banner-content" });
    const greeting = this.getGreeting();
    const welcomeText = this.plugin.settings.bannerTitle || "\u6B22\u8FCE\u56DE\u6765";
    content.createEl("h1", { text: `${greeting.emoji} ${greeting.text}\uFF0C${welcomeText}\uFF01`, cls: "jhua-greeting" });
    const dateTimeEl = content.createDiv({ cls: "jhua-datetime" });
    dateTimeEl.createEl("span", { text: this.getFormattedDateTime() });
    const countdownsEl = content.createDiv({ cls: "jhua-countdowns" });
    for (const countdown of this.plugin.settings.countdowns) {
      const days = this.getDaysUntil(countdown.date);
      if (days !== null) {
        const countdownItem = countdownsEl.createDiv({ cls: "jhua-countdown-item" });
        countdownItem.createEl("span", { text: `\u23F0 \u8DDD\u79BB${countdown.name}\u8FD8\u6709 ${days} \u5929` });
      }
    }
    const buttonsContainer = banner.createDiv({ cls: "jhua-banner-buttons" });
    const refreshBtn = buttonsContainer.createEl("button", { cls: "jhua-banner-refresh" });
    refreshBtn.innerHTML = `<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2"><path d="M23 4v6h-6"/><path d="M1 20v-6h6"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/></svg>`;
    refreshBtn.addEventListener("click", async () => {
      await this.render();
    });
    const settingsBtn = buttonsContainer.createEl("button", { cls: "jhua-banner-settings" });
    settingsBtn.innerHTML = `<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>`;
    settingsBtn.addEventListener("click", () => {
      new BannerSettingsModal(this.app, this.plugin).open();
    });
  }
  renderNavigation(container) {
    const navSection = container.createDiv({ cls: "jhua-nav-section" });
    navSection.createEl("h2", { text: "\u5FEB\u6377\u5BFC\u822A" });
    const navGrid = navSection.createDiv({ cls: "jhua-nav-grid" });
    for (const category of this.plugin.settings.categories) {
      const categoryCard = navGrid.createDiv({ cls: "jhua-category-card" });
      categoryCard.style.setProperty("--category-color", category.color);
      const header = categoryCard.createDiv({ cls: "jhua-category-header" });
      header.createEl("span", { text: `${category.icon} ${category.name}`, cls: "jhua-category-title" });
      const settingsBtn = header.createEl("button", { cls: "jhua-nav-settings-btn", text: "\u2699\uFE0F" });
      settingsBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        new NavigationSettingsModal(this.app, this.plugin, () => this.render()).open();
      });
      const itemsContainer = categoryCard.createDiv({ cls: "jhua-category-items" });
      for (const item of category.items) {
        const navItem = itemsContainer.createDiv({ cls: "jhua-nav-item" });
        navItem.createEl("span", { text: `${item.icon} ${item.name}` });
        navItem.addEventListener("click", () => {
          const path = item.path;
          if (path.startsWith("file:///")) {
            const localPath = path.replace("file:///", "").replace(/\//g, "\\");
            try {
              const { shell } = require("electron");
              shell.openPath(localPath);
            } catch (e) {
              console.error("Failed to open external file:", e);
            }
            return;
          }
          if (/^[A-Za-z]:[\\\/]/.test(path)) {
            try {
              const { shell } = require("electron");
              shell.openPath(path);
            } catch (e) {
              console.error("Failed to open external file:", e);
            }
            return;
          }
          if (path.startsWith("obsidian://")) {
            window.open(path, "_blank");
            return;
          }
          if (path.startsWith("http://") || path.startsWith("https://")) {
            window.open(path, "_blank");
            return;
          }
          this.app.workspace.openLinkText(path, "", true);
        });
      }
    }
  }
  async renderTodoList(container) {
    const todoSection = container.createDiv({ cls: "jhua-todo-section" });
    const header = todoSection.createDiv({ cls: "jhua-todo-header" });
    header.createEl("h2", { text: "\u{1F4DD} \u5F85\u529E\u4E8B\u9879" });
    const addBtn = header.createEl("button", { text: "+ \u521B\u5EFA", cls: "jhua-todo-add-btn" });
    addBtn.addEventListener("click", () => {
      new AddTodoModal(this.app, this.todoManager, this.plugin, () => this.render()).open();
    });
    const todoList = todoSection.createDiv({ cls: "jhua-todo-list" });
    const cachedTodos = this.todoManager.getTodos();
    const weeklyTodos = await this.todoManager.getWeeklyTodosFromDailyNotes();
    const uniqueWeeklyTodos = weeklyTodos.filter(
      (wt) => !cachedTodos.some((ct) => ct.content === wt.content && ct.dueDate === wt.dueDate)
    );
    const allTodos = [...cachedTodos, ...uniqueWeeklyTodos];
    const priorityOrder = { "high": 0, "medium": 1, "low": 2 };
    const sortedTodos = [...allTodos].sort((a, b) => {
      if (a.completed !== b.completed) {
        return a.completed ? 1 : -1;
      }
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    });
    for (const todo of sortedTodos) {
      const dueStatus = this.getDueDateStatus(todo.dueDate);
      const completedClass = todo.completed ? "completed" : "";
      const isFromDailyNote = todo.id.startsWith("daily-");
      const todoItem = todoList.createDiv({
        cls: `jhua-todo-item priority-${todo.priority} ${dueStatus} ${completedClass}`
      });
      const checkbox = todoItem.createEl("input", { type: "checkbox", cls: "jhua-todo-checkbox" });
      checkbox.checked = todo.completed;
      if (!isFromDailyNote) {
        checkbox.addEventListener("change", async () => {
          await this.todoManager.toggleTodo(todo.id);
          this.render();
        });
      } else {
        checkbox.addEventListener("change", async () => {
          if (todo.dueDate) {
            await this.todoManager.syncTodoStatusToDailyNote(todo.dueDate, todo.content, !todo.completed);
            this.render();
          }
        });
      }
      const todoContent = todoItem.createDiv({ cls: "jhua-todo-content" });
      const dateLabel = todo.dueDate ? `(${todo.dueDate}) ` : "";
      todoContent.createEl("span", { text: `${dateLabel}${todo.content}`, cls: "jhua-todo-text" });
      if (todo.dueDate) {
        todoContent.style.cursor = "pointer";
        todoContent.addEventListener("click", (e) => {
          if (e.target.tagName !== "INPUT") {
            const dailyNotePath = this.todoManager.getDailyNotePath(todo.dueDate);
            this.app.workspace.openLinkText(dailyNotePath, "", true);
          }
        });
      }
      if (todo.tags && todo.tags.length > 0) {
        const tagsEl = todoItem.createDiv({ cls: "jhua-todo-tags" });
        for (const tag of todo.tags) {
          tagsEl.createEl("span", { text: `#${tag}`, cls: "jhua-todo-tag" });
        }
      }
      if (!isFromDailyNote) {
        const deleteBtn = todoItem.createEl("button", { text: "\xD7", cls: "jhua-todo-delete" });
        deleteBtn.addEventListener("click", async () => {
          await this.todoManager.deleteTodo(todo.id);
          this.render();
        });
      }
    }
    if (sortedTodos.length === 0) {
      todoList.createDiv({ cls: "jhua-empty-state", text: "\u6682\u65E0\u5F85\u529E\u4E8B\u9879\uFF0C\u70B9\u51FB\u6DFB\u52A0\u6309\u94AE\u521B\u5EFA" });
    }
  }
  getDueDateStatus(dueDate) {
    if (!dueDate)
      return "";
    try {
      const due = new Date(dueDate);
      const today = /* @__PURE__ */ new Date();
      today.setHours(0, 0, 0, 0);
      due.setHours(0, 0, 0, 0);
      const diff = (due.getTime() - today.getTime()) / (1e3 * 60 * 60 * 24);
      if (diff < 0)
        return "due-overdue";
      if (diff === 0)
        return "due-today";
      return "due-future";
    } catch (e) {
      return "";
    }
  }
  renderRecentFiles(container) {
    const recentSection = container.createDiv({ cls: "jhua-recent-section" });
    recentSection.createEl("h2", { text: "\u{1F4C4} \u6700\u8FD1\u6587\u6863" });
    const recentList = recentSection.createDiv({ cls: "jhua-recent-list" });
    const files = this.app.vault.getMarkdownFiles().sort((a, b) => b.stat.mtime - a.stat.mtime).slice(0, 10);
    for (const file of files) {
      const fileItem = recentList.createDiv({ cls: "jhua-recent-item" });
      fileItem.createEl("span", { text: file.basename, cls: "jhua-recent-name" });
      fileItem.createEl("span", { text: this.formatRelativeTime(file.stat.mtime), cls: "jhua-recent-time" });
      fileItem.addEventListener("click", () => {
        this.app.workspace.openLinkText(file.path, "", true);
      });
    }
  }
  // ==================== 待整理区域 ====================
  renderUnorganizedFiles(container) {
    const section = container.createDiv({ cls: "jhua-unorganized-section" });
    const header = section.createDiv({ cls: "jhua-unorganized-header" });
    header.createEl("h2", { text: "\u{1F4DA} \u5F85\u6574\u7406" });
    if (this.plugin.settings.unorganizedCreateUri) {
      const createBtn = header.createEl("button", { text: "+ \u521B\u5EFA", cls: "jhua-section-create-btn" });
      createBtn.addEventListener("click", () => {
        window.open(this.plugin.settings.unorganizedCreateUri, "_blank");
      });
    }
    const filesList = section.createDiv({ cls: "jhua-unorganized-list" });
    const targetFolder = "00-\u9879\u76EE\uFF08Projects\uFF09/05-\u788E\u7247\u96C6\u5408";
    const allFiles = this.app.vault.getMarkdownFiles();
    const unorganizedFiles = allFiles.filter((file) => file.path.startsWith(targetFolder));
    unorganizedFiles.sort((a, b) => b.stat.mtime - a.stat.mtime);
    if (unorganizedFiles.length === 0) {
      filesList.createDiv({ cls: "jhua-empty-state", text: "\u8BE5\u76EE\u5F55\u4E0B\u6682\u65E0\u6587\u4EF6" });
      return;
    }
    for (const file of unorganizedFiles) {
      const fileItem = filesList.createDiv({ cls: "jhua-unorganized-item" });
      const nameEl = fileItem.createDiv({ cls: "jhua-unorganized-name" });
      nameEl.createEl("span", { text: file.basename });
      const tagsEl = fileItem.createDiv({ cls: "jhua-unorganized-tags" });
      this.getFileTags(file).then((tags) => {
        if (tags && tags.length > 0) {
          const tagColors = {
            "work": "jhua-tag-work",
            "study": "jhua-tag-study",
            "life": "jhua-tag-life",
            "project": "jhua-tag-project",
            "plan": "jhua-tag-plan",
            "pending": "jhua-tag-pending",
            "progress": "jhua-tag-progress",
            "done": "jhua-tag-done",
            "important": "jhua-tag-important",
            "idea": "jhua-tag-idea"
          };
          for (const tag of tags) {
            const cleanTag = tag.replace(/^- /, "").trim().toLowerCase();
            const tagEl = tagsEl.createEl("span", { text: `#${cleanTag}`, cls: "jhua-tag" });
            const tagClass = tagColors[cleanTag];
            if (tagClass) {
              tagEl.addClass(tagClass);
            }
          }
        }
      });
      fileItem.addEventListener("click", () => {
        this.app.workspace.openLinkText(file.path, "", true);
      });
    }
  }
  // ==================== 项目跟踪区域 ====================
  renderProjectTracking(container) {
    const section = container.createDiv({ cls: "jhua-project-tracking-section" });
    const header = section.createDiv({ cls: "jhua-project-tracking-header" });
    header.createEl("h2", { text: "\u{1F4CA} \u9879\u76EE\u8DDF\u8E2A" });
    if (this.plugin.settings.projectCreateUri) {
      const createBtn = header.createEl("button", { text: "+ \u521B\u5EFA", cls: "jhua-section-create-btn" });
      createBtn.addEventListener("click", () => {
        window.open(this.plugin.settings.projectCreateUri, "_blank");
      });
    }
    const filesList = section.createDiv({ cls: "jhua-project-list" });
    const targetFolder = "00-\u9879\u76EE\uFF08Projects\uFF09";
    const allFiles = this.app.vault.getMarkdownFiles();
    const projectFiles = allFiles.filter((file) => file.path.startsWith(targetFolder));
    this.loadProjectFiles(filesList, projectFiles);
  }
  async loadProjectFiles(filesList, projectFiles) {
    const projectItems = [];
    for (const file of projectFiles) {
      const metadata = await this.getFileMetadata(file);
      const tags = await this.getFileTags(file);
      if (metadata && metadata.type && metadata.ddl && metadata.progress) {
        projectItems.push({
          file,
          metadata,
          tags
        });
      }
    }
    const tableHeader = filesList.createDiv({ cls: "jhua-project-table-header" });
    const columns = [
      { key: "name", label: "\u9879\u76EE\u540D\u79F0", class: "jhua-th-name" },
      { key: "type", label: "\u7C7B\u578B", class: "jhua-th-type" },
      { key: "progress", label: "\u8FDB\u5EA6", class: "jhua-th-progress" },
      { key: "remark", label: "\u5907\u6CE8", class: "jhua-th-remark" },
      { key: "tags", label: "\u6807\u7B7E", class: "jhua-th-tags" },
      { key: "ddl", label: "\u622A\u6B62\u65E5\u671F", class: "jhua-th-ddl" }
    ];
    for (const col of columns) {
      const th = tableHeader.createEl("span", { cls: `jhua-project-th ${col.class}` });
      th.createEl("span", { text: col.label });
      const sortIndicator = th.createEl("span", { cls: "jhua-sort-indicator" });
      if (this.projectSortState.column === col.key) {
        sortIndicator.textContent = this.projectSortState.direction === "asc" ? " \u2191" : " \u2193";
        sortIndicator.addClass("jhua-sort-active");
      }
      th.addEventListener("click", () => {
        if (this.projectSortState.column === col.key) {
          this.projectSortState.direction = this.projectSortState.direction === "asc" ? "desc" : "asc";
        } else {
          this.projectSortState.column = col.key;
          this.projectSortState.direction = "asc";
        }
        this.render();
      });
      th.addClass("jhua-sortable");
    }
    const sortedItems = this.sortProjectItems(projectItems);
    if (sortedItems.length === 0) {
      filesList.createDiv({ cls: "jhua-empty-state", text: "\u8BE5\u76EE\u5F55\u4E0B\u6682\u65E0\u7B26\u5408\u6761\u4EF6\u7684\u9879\u76EE\u6587\u4EF6\uFF08\u9700\u8981type\u3001ddl\u3001progress\u5143\u6570\u636E\uFF09" });
      return;
    }
    for (const item of sortedItems) {
      const row = filesList.createDiv({ cls: "jhua-project-row" });
      const nameCell = row.createDiv({ cls: "jhua-project-cell jhua-cell-name" });
      nameCell.createEl("span", { text: item.file.basename, cls: "jhua-project-link" });
      nameCell.addEventListener("click", () => {
        this.app.workspace.openLinkText(item.file.path, "", true);
      });
      const typeCell = row.createDiv({ cls: "jhua-project-cell jhua-cell-type" });
      const typeBadge = typeCell.createEl("span", { text: item.metadata.type, cls: "jhua-meta-badge jhua-type-badge" });
      const typeColors = {
        "\u5DE5\u4F5C": "jhua-type-work",
        "\u5B66\u4E60": "jhua-type-study",
        "\u751F\u6D3B": "jhua-type-life",
        "\u9879\u76EE": "jhua-type-project",
        "\u8BA1\u5212": "jhua-type-plan",
        "\u5176\u4ED6": "jhua-type-other",
        "\u5F85\u5B8C\u6210": "jhua-status-pending",
        "\u8FDB\u884C\u4E2D": "jhua-status-progress",
        "\u5DF2\u5B8C\u6210": "jhua-status-done"
      };
      const typeClass = typeColors[item.metadata.type] || "jhua-type-default";
      typeBadge.addClass(typeClass);
      typeBadge.addEventListener("click", async (e) => {
        e.stopPropagation();
        e.preventDefault();
        new TypeSelectModal(
          this.app,
          "\u9009\u62E9\u7C7B\u578B",
          ["\u5F85\u5B8C\u6210", "\u8FDB\u884C\u4E2D", "\u5DF2\u5B8C\u6210", "\u5DE5\u4F5C", "\u5B66\u4E60", "\u751F\u6D3B", "\u9879\u76EE", "\u8BA1\u5212", "\u5176\u4ED6"],
          item.metadata.type,
          async (newType) => {
            if (newType !== null && newType !== item.metadata.type) {
              const success = await this.updateFileField(item.file, "type", newType);
              if (success) {
                item.metadata.type = newType;
                typeBadge.textContent = newType;
                typeBadge.className = "jhua-meta-badge jhua-type-badge";
                const newClass = typeColors[newType] || "jhua-type-default";
                typeBadge.addClass(newClass);
                new import_obsidian.Notice("\u7C7B\u578B\u5DF2\u66F4\u65B0");
              } else {
                new import_obsidian.Notice("\u66F4\u65B0\u5931\u8D25");
              }
            }
          }
        ).open();
      });
      const progressCell = row.createDiv({ cls: "jhua-project-cell jhua-cell-progress" });
      const progressValue = parseFloat(item.metadata.progress) || 0;
      const progressBadge = progressCell.createEl("span", { cls: "jhua-meta-badge jhua-progress-badge" });
      progressBadge.textContent = `${progressValue}%`;
      progressBadge.addEventListener("click", async (e) => {
        e.stopPropagation();
        e.preventDefault();
        new TypeSelectModal(
          this.app,
          "\u9009\u62E9\u8FDB\u5EA6",
          ["0", "30", "60", "90", "100"],
          item.metadata.progress || "0",
          async (newProgress) => {
            if (newProgress !== null && newProgress !== item.metadata.progress) {
              const value = parseInt(newProgress) || 0;
              const success = await this.updateFileField(item.file, "progress", newProgress);
              if (success) {
                item.metadata.progress = newProgress;
                progressBadge.textContent = `${value}%`;
                progressFill.style.width = `${value}%`;
                progressFill.className = "jhua-progress-fill";
                if (value >= 80) {
                  progressFill.addClass("jhua-progress-high");
                } else if (value >= 50) {
                  progressFill.addClass("jhua-progress-medium");
                } else {
                  progressFill.addClass("jhua-progress-low");
                }
                new import_obsidian.Notice("\u8FDB\u5EA6\u5DF2\u66F4\u65B0");
              } else {
                new import_obsidian.Notice("\u66F4\u65B0\u5931\u8D25");
              }
            }
          }
        ).open();
      });
      const progressBar = progressCell.createDiv({ cls: "jhua-progress-bar" });
      const progressFill = progressBar.createDiv({ cls: "jhua-progress-fill" });
      progressFill.style.width = `${Math.min(progressValue, 100)}%`;
      if (progressValue >= 80) {
        progressFill.addClass("jhua-progress-high");
      } else if (progressValue >= 50) {
        progressFill.addClass("jhua-progress-medium");
      } else {
        progressFill.addClass("jhua-progress-low");
      }
      const remarkCell = row.createDiv({ cls: "jhua-project-cell jhua-cell-remark" });
      const remarkText = item.metadata.remark || "\u70B9\u51FB\u6DFB\u52A0";
      const remarkSpan = remarkCell.createEl("span", { text: remarkText, cls: "jhua-remark-text" });
      remarkSpan.addEventListener("click", async (e) => {
        e.stopPropagation();
        e.preventDefault();
        new InputPromptModal(
          this.app,
          "\u7F16\u8F91\u5907\u6CE8",
          "\u8BF7\u8F93\u5165\u5907\u6CE8\u5185\u5BB9",
          item.metadata.remark || "",
          async (newRemark) => {
            if (newRemark !== null && newRemark !== item.metadata.remark) {
              const success = await this.updateFileRemark(item.file, newRemark);
              if (success) {
                item.metadata.remark = newRemark;
                remarkSpan.textContent = newRemark || "\u70B9\u51FB\u6DFB\u52A0";
                new import_obsidian.Notice("\u5907\u6CE8\u5DF2\u66F4\u65B0");
              } else {
                new import_obsidian.Notice("\u66F4\u65B0\u5931\u8D25");
              }
            }
          }
        ).open();
      });
      const tagsCell = row.createDiv({ cls: "jhua-project-cell jhua-cell-tags" });
      const tagColors = {
        "\u5F85\u5B8C\u6210": "jhua-tag-pending",
        "\u8FDB\u884C\u4E2D": "jhua-tag-progress",
        "\u5DF2\u5B8C\u6210": "jhua-tag-done",
        "\u5BA1\u6838\u4E2D": "jhua-tag-review",
        "\u91CD\u8981": "jhua-tag-important",
        "\u7D27\u6025": "jhua-tag-urgent",
        "\u5DE5\u4F5C": "jhua-tag-work",
        "\u5B66\u4E60": "jhua-tag-study",
        "\u751F\u6D3B": "jhua-tag-life",
        "\u9879\u76EE": "jhua-tag-project",
        "\u8BA1\u5212": "jhua-tag-plan",
        "\u60F3\u6CD5": "jhua-tag-idea"
      };
      if (item.tags && item.tags.length > 0) {
        for (let i = 0; i < item.tags.length; i++) {
          const tag = item.tags[i];
          const cleanTag = tag.replace(/^- /, "").trim();
          const tagEl = tagsCell.createEl("span", { text: `#${cleanTag}`, cls: "jhua-tag" });
          const tagClass = tagColors[cleanTag];
          if (tagClass) {
            tagEl.addClass(tagClass);
          }
        }
      } else {
        tagsCell.createEl("span", { text: "\u70B9\u51FB\u6DFB\u52A0", cls: "jhua-tag-placeholder" });
      }
      tagsCell.addEventListener("click", async (e) => {
        e.stopPropagation();
        e.preventDefault();
        new TagManageModal(
          this.app,
          item.file,
          item.tags,
          async (newTags) => {
            const success = await this.updateFileTags(item.file, newTags);
            if (success) {
              new import_obsidian.Notice("\u6807\u7B7E\u5DF2\u66F4\u65B0");
              this.render();
            } else {
              new import_obsidian.Notice("\u66F4\u65B0\u5931\u8D25");
            }
          }
        ).open();
      });
      const ddlCell = row.createDiv({ cls: "jhua-project-cell jhua-cell-ddl" });
      const ddlDate = new Date(item.metadata.ddl);
      const today = /* @__PURE__ */ new Date();
      const daysLeft = Math.ceil((ddlDate.getTime() - today.getTime()) / (1e3 * 60 * 60 * 24));
      const ddlBadge = ddlCell.createEl("span", { cls: "jhua-meta-badge jhua-ddl-badge" });
      ddlBadge.textContent = item.metadata.ddl;
      if (daysLeft < 0) {
        ddlBadge.addClass("jhua-ddl-overdue");
      } else if (daysLeft <= 3) {
        ddlBadge.addClass("jhua-ddl-urgent");
      } else if (daysLeft <= 7) {
        ddlBadge.addClass("jhua-ddl-soon");
      }
      ddlBadge.addEventListener("click", async (e) => {
        e.stopPropagation();
        e.preventDefault();
        new DateSelectModal(
          this.app,
          "\u9009\u62E9\u622A\u6B62\u65E5\u671F",
          item.metadata.ddl || "",
          async (newDdl) => {
            if (newDdl !== null && newDdl !== item.metadata.ddl) {
              const success = await this.updateFileField(item.file, "ddl", newDdl);
              if (success) {
                item.metadata.ddl = newDdl;
                ddlBadge.textContent = newDdl || "\u672A\u8BBE\u7F6E";
                ddlBadge.className = "jhua-meta-badge jhua-ddl-badge";
                if (newDdl) {
                  const newDdlDate = new Date(newDdl);
                  const newDaysLeft = Math.ceil((newDdlDate.getTime() - today.getTime()) / (1e3 * 60 * 60 * 24));
                  if (newDaysLeft < 0) {
                    ddlBadge.addClass("jhua-ddl-overdue");
                  } else if (newDaysLeft <= 3) {
                    ddlBadge.addClass("jhua-ddl-urgent");
                  } else if (newDaysLeft <= 7) {
                    ddlBadge.addClass("jhua-ddl-soon");
                  }
                }
                new import_obsidian.Notice("\u622A\u6B62\u65E5\u671F\u5DF2\u66F4\u65B0");
              } else {
                new import_obsidian.Notice("\u66F4\u65B0\u5931\u8D25");
              }
            }
          }
        ).open();
      });
    }
  }
  sortProjectItems(items) {
    const sortedItems = [...items];
    const { column, direction } = this.projectSortState;
    const multiplier = direction === "asc" ? 1 : -1;
    sortedItems.sort((a, b) => {
      let compareResult = 0;
      switch (column) {
        case "name":
          compareResult = a.file.basename.localeCompare(b.file.basename, "zh-CN");
          break;
        case "type":
          compareResult = (a.metadata.type || "").localeCompare(b.metadata.type || "", "zh-CN");
          break;
        case "progress":
          const progressA = parseFloat(a.metadata.progress) || 0;
          const progressB = parseFloat(b.metadata.progress) || 0;
          compareResult = progressA - progressB;
          break;
        case "remark":
          compareResult = (a.metadata.remark || "").localeCompare(b.metadata.remark || "", "zh-CN");
          break;
        case "tags":
          const tagsA = (a.tags || []).length;
          const tagsB = (b.tags || []).length;
          compareResult = tagsA - tagsB;
          break;
        case "ddl":
          try {
            const ddlA = new Date(a.metadata.ddl);
            const ddlB = new Date(b.metadata.ddl);
            compareResult = ddlA.getTime() - ddlB.getTime();
          } catch (e) {
            compareResult = 0;
          }
          break;
      }
      return compareResult * multiplier;
    });
    return sortedItems;
  }
  // ==================== 文件元数据操作 ====================
  async getFileTags(file) {
    try {
      const content = await this.app.vault.read(file);
      const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
      if (frontmatterMatch) {
        const frontmatter = frontmatterMatch[1];
        
        // 先尝试匹配列表格式（YAML 列表）
        const listMatch = frontmatter.match(/tags:\s*\n((\s+- .+\n?)+)/);
        if (listMatch) {
          const tags = listMatch[1].match(/- (.+)/g);
          if (tags) {
            return tags.map((t) => t.replace(/- /, "").trim());
          }
        }
        
        // 再尝试匹配数组格式（单行数组）
        const arrayMatch = frontmatter.match(/tags:\s*\[([^\]]+)\]/);
        if (arrayMatch) {
          let tags = arrayMatch[1];
          tags = tags.replace(/["']/g, "").split(",").map((t) => t.trim()).filter((t) => t);
          return tags;
        }
        
        // 最后尝试匹配单行格式
        const singleMatch = frontmatter.match(/tags:\s*([^\[\n]+)/);
        if (singleMatch) {
          const tagStr = singleMatch[1].trim();
          if (tagStr) {
            return tagStr.split(",").map((t) => t.trim()).filter((t) => t);
          }
        }
      }
      return [];
    } catch (e) {
      console.error("获取标签失败:", e);
      return [];
    }
  }
  async getFileMetadata(file) {
    try {
      const content = await this.app.vault.read(file);
      const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
      if (frontmatterMatch) {
        const frontmatter = frontmatterMatch[1];
        const metadata = {};
        const typeMatch = frontmatter.match(/type:\s*(.+)/);
        if (typeMatch) {
          metadata.type = typeMatch[1].trim().replace(/["']/g, "");
        }
        const ddlMatch = frontmatter.match(/ddl:\s*(.+)/);
        if (ddlMatch) {
          metadata.ddl = ddlMatch[1].trim().replace(/["']/g, "");
        }
        const progressMatch = frontmatter.match(/progress:\s*(.+)/);
        if (progressMatch) {
          metadata.progress = progressMatch[1].trim().replace(/["']/g, "");
        }
        const remarkMatch = frontmatter.match(/remark:\s*(.+)/);
        if (remarkMatch) {
          metadata.remark = remarkMatch[1].trim().replace(/["']/g, "");
        }
        return metadata;
      }
      return null;
    } catch (e) {
      return null;
    }
  }
  async updateFileField(file, field, value) {
    try {
      const content = await this.app.vault.read(file);
      const frontmatterMatch = content.match(/^(---\n[\s\S]*?\n---)/);
      if (frontmatterMatch) {
        let frontmatter = frontmatterMatch[1];
        const fieldRegex = new RegExp(`${field}:\\s*.+`);
        if (fieldRegex.test(frontmatter)) {
          frontmatter = frontmatter.replace(fieldRegex, `${field}: ${value}`);
        } else {
          frontmatter = frontmatter.replace(/\n---$/, `
${field}: ${value}
---`);
        }
        const newContent = content.replace(/^---\n[\s\S]*?\n---/, frontmatter);
        await this.app.vault.modify(file, newContent);
        return true;
      }
      return false;
    } catch (e) {
      console.error(`\u66F4\u65B0${field}\u5931\u8D25:`, e);
      return false;
    }
  }
  async updateFileRemark(file, newRemark) {
    try {
      const content = await this.app.vault.read(file);
      const frontmatterMatch = content.match(/^(---\n[\s\S]*?\n---)/);
      if (frontmatterMatch) {
        let frontmatter = frontmatterMatch[1];
        if (/remark:\s*.+/.test(frontmatter)) {
          frontmatter = frontmatter.replace(/remark:\s*.+/, `remark: ${newRemark}`);
        } else {
          frontmatter = frontmatter.replace(/\n---$/, `
remark: ${newRemark}
---`);
        }
        const newContent = content.replace(/^---\n[\s\S]*?\n---/, frontmatter);
        await this.app.vault.modify(file, newContent);
        return true;
      }
      return false;
    } catch (e) {
      console.error("\u66F4\u65B0remark\u5931\u8D25:", e);
      return false;
    }
  }
  async updateFileTags(file, tags) {
    try {
      const content = await this.app.vault.read(file);
      const frontmatterMatch = content.match(/^(---\n[\s\S]*?\n---)/);
      if (frontmatterMatch) {
        let frontmatter = frontmatterMatch[1];
        const tagsYaml = tags.length > 0 ? `tags:
${tags.map((t) => `  - ${t}`).join("\n")}` : "tags: []";
        if (/tags:\s*\n(\s+- .+\n?)+/.test(frontmatter)) {
          frontmatter = frontmatter.replace(/tags:\s*\n(\s+- .+\n?)+/, tagsYaml + "\n");
        } else if (/tags:\s*\[.+\]/.test(frontmatter)) {
          frontmatter = frontmatter.replace(/tags:\s*\[.+\]/, tagsYaml);
        } else if (/tags:\s*.+/.test(frontmatter)) {
          frontmatter = frontmatter.replace(/tags:\s*.+/, tagsYaml);
        } else {
          frontmatter = frontmatter.replace(/\n---$/, `
${tagsYaml}
---`);
        }
        const newContent = content.replace(/^---\n[\s\S]*?\n---/, frontmatter);
        await this.app.vault.modify(file, newContent);
        return true;
      }
      return false;
    } catch (e) {
      console.error("\u66F4\u65B0tags\u5931\u8D25:", e);
      return false;
    }
  }
  getGreeting() {
    const hour = (/* @__PURE__ */ new Date()).getHours();
    if (hour < 6)
      return { emoji: "\u{1F319}", text: "\u591C\u6DF1\u4E86" };
    if (hour < 12)
      return { emoji: "\u2600\uFE0F", text: "\u65E9\u4E0A\u597D" };
    if (hour < 18)
      return { emoji: "\u{1F324}\uFE0F", text: "\u4E0B\u5348\u597D" };
    return { emoji: "\u{1F319}", text: "\u665A\u4E0A\u597D" };
  }
  getFormattedDateTime() {
    const now = /* @__PURE__ */ new Date();
    const days = ["\u661F\u671F\u65E5", "\u661F\u671F\u4E00", "\u661F\u671F\u4E8C", "\u661F\u671F\u4E09", "\u661F\u671F\u56DB", "\u661F\u671F\u4E94", "\u661F\u671F\u516D"];
    return `${now.getFullYear()}\u5E74${now.getMonth() + 1}\u6708${now.getDate()}\u65E5 ${days[now.getDay()]} ${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`;
  }
  updateDateTime() {
    const dateTimeEl = this.containerEl.querySelector(".jhua-datetime span");
    if (dateTimeEl) {
      dateTimeEl.textContent = this.getFormattedDateTime();
    }
  }
  getDaysUntil(dateStr) {
    try {
      const target = new Date(dateStr);
      const now = /* @__PURE__ */ new Date();
      const diff = target.getTime() - now.getTime();
      return Math.ceil(diff / (1e3 * 60 * 60 * 24));
    } catch (e) {
      return null;
    }
  }
  formatRelativeTime(timestamp) {
    const diff = Date.now() - timestamp;
    const minutes = Math.floor(diff / 6e4);
    const hours = Math.floor(diff / 36e5);
    const days = Math.floor(diff / 864e5);
    if (minutes < 1)
      return "\u521A\u521A";
    if (minutes < 60)
      return `${minutes}\u5206\u949F\u524D`;
    if (hours < 24)
      return `${hours}\u5C0F\u65F6\u524D`;
    return `${days}\u5929\u524D`;
  }
};
var InputPromptModal = class extends import_obsidian.Modal {
  constructor(app, title, placeholder = "", defaultValue = "", onSubmit) {
    super(app);
    this.title = title;
    this.placeholder = placeholder;
    this.defaultValue = defaultValue;
    this.onSubmit = onSubmit;
    this.inputValue = defaultValue;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("jhua-input-prompt-modal");
    contentEl.createEl("h2", { text: this.title });
    new import_obsidian.Setting(contentEl).addText((text) => text.setPlaceholder(this.placeholder).setValue(this.defaultValue).onChange((value) => {
      this.inputValue = value;
    }).inputEl.style.width = "100%");
    new import_obsidian.Setting(contentEl).addButton((button) => button.setButtonText("\u53D6\u6D88").onClick(() => {
      this.close();
    })).addButton((button) => button.setButtonText("\u786E\u5B9A").setCta().onClick(() => {
      this.onSubmit(this.inputValue);
      this.close();
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var TypeSelectModal = class extends import_obsidian.Modal {
  constructor(app, title, options, currentValue, onSelect) {
    super(app);
    this.title = title;
    this.options = options;
    this.currentValue = currentValue;
    this.onSelect = onSelect;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("jhua-type-select-modal");
    contentEl.createEl("h2", { text: this.title });
    const optionsContainer = contentEl.createDiv({ cls: "jhua-select-options" });
    for (const option of this.options) {
      const optionEl = optionsContainer.createDiv({ cls: "jhua-select-option" });
      if (option === this.currentValue) {
        optionEl.addClass("jhua-select-option-active");
      }
      optionEl.createEl("span", { text: option });
      optionEl.addEventListener("click", () => {
        this.onSelect(option);
        this.close();
      });
    }
    new import_obsidian.Setting(contentEl).addButton(
      (button) => button.setButtonText("\u53D6\u6D88").onClick(() => {
        this.close();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var DateSelectModal = class extends import_obsidian.Modal {
  constructor(app, title, currentValue, onSelect) {
    super(app);
    this.title = title;
    this.currentValue = currentValue;
    this.onSelect = onSelect;
    this.selectedDate = currentValue;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("jhua-date-select-modal");
    contentEl.createEl("h2", { text: this.title });
    const dateInput = contentEl.createEl("input", { cls: "jhua-date-input" });
    dateInput.type = "date";
    dateInput.value = this.currentValue || (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    dateInput.addEventListener("change", () => {
      this.selectedDate = dateInput.value;
    });
    const buttonsContainer = contentEl.createDiv({ cls: "jhua-date-buttons" });
    const todayBtn = buttonsContainer.createEl("button", { text: "\u4ECA\u5929", cls: "jhua-date-today-btn" });
    todayBtn.addEventListener("click", () => {
      const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
      dateInput.value = today;
      this.selectedDate = today;
    });
    const clearBtn = buttonsContainer.createEl("button", { text: "\u6E05\u9664", cls: "jhua-date-clear-btn" });
    clearBtn.addEventListener("click", () => {
      dateInput.value = "";
      this.selectedDate = "";
    });
    new import_obsidian.Setting(contentEl).addButton(
      (button) => button.setButtonText("\u53D6\u6D88").onClick(() => {
        this.close();
      })
    ).addButton(
      (button) => button.setButtonText("\u786E\u5B9A").setCta().onClick(() => {
        this.onSelect(this.selectedDate);
        this.close();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var TagManageModal = class extends import_obsidian.Modal {
  constructor(app, file, tags, onSave) {
    super(app);
    this.file = file;
    this.tags = [...tags || []];
    this.onSave = onSave;
    this.tagColors = {
      "\u5F85\u5B8C\u6210": "jhua-tag-pending",
      "\u8FDB\u884C\u4E2D": "jhua-tag-progress",
      "\u5DF2\u5B8C\u6210": "jhua-tag-done",
      "\u5BA1\u6838\u4E2D": "jhua-tag-review",
      "\u91CD\u8981": "jhua-tag-important",
      "\u7D27\u6025": "jhua-tag-urgent",
      "\u5DE5\u4F5C": "jhua-tag-work",
      "\u5B66\u4E60": "jhua-tag-study",
      "\u751F\u6D3B": "jhua-tag-life",
      "\u9879\u76EE": "jhua-tag-project",
      "\u8BA1\u5212": "jhua-tag-plan",
      "\u60F3\u6CD5": "jhua-tag-idea"
    };
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("jhua-tag-manage-modal");
    contentEl.createEl("h2", { text: "\u6807\u7B7E\u7BA1\u7406" });
    // 创建标签列表容器
    this.tagsListContainer = contentEl.createDiv({ cls: "jhua-tag-manage-list" });
    this.renderTags();
    const inputContainer = contentEl.createDiv({ cls: "jhua-tag-input-container" });
    const input = inputContainer.createEl("input", {
      cls: "jhua-tag-input",
      attr: { placeholder: "\u8F93\u5165\u65B0\u6807\u7B7E\uFF0C\u6309\u56DE\u8F66\u6DFB\u52A0" }
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && input.value.trim()) {
        this.tags.push(input.value.trim());
        input.value = "";
        this.renderTags();
      }
    });
    new import_obsidian.Setting(contentEl).addButton(
      (button) => button.setButtonText("\u53D6\u6D88").onClick(() => {
        this.close();
      })
    ).addButton(
      (button) => button.setButtonText("\u4FDD\u5B58").setCta().onClick(async () => {
        await this.onSave(this.tags);
        this.close();
      })
    );
  }
  renderTags() {
    if (!this.tagsListContainer) return;
    this.tagsListContainer.empty();
    if (this.tags.length === 0) {
      this.tagsListContainer.createDiv({ cls: "jhua-tag-empty", text: "\u6682\u65E0\u6807\u7B7E\uFF0C\u8BF7\u6DFB\u52A0" });
      return;
    }
    for (let i = 0; i < this.tags.length; i++) {
      const tag = this.tags[i];
      const tagItem = this.tagsListContainer.createDiv({ cls: "jhua-tag-manage-item" });
      const tagEl = tagItem.createEl("span", { text: `#${tag}`, cls: "jhua-tag" });
      const tagClass = this.tagColors[tag];
      if (tagClass) {
        tagEl.addClass(tagClass);
      }
      const editBtn = tagItem.createEl("button", { cls: "jhua-tag-edit-btn", text: "\u270E" });
      editBtn.addEventListener("click", () => {
        new InputPromptModal(
          this.app,
          "\u7F16\u8F91\u6807\u7B7E",
          "\u8BF7\u8F93\u5165\u65B0\u6807\u7B7E\uFF08\u4E0D\u9700\u8981\u8F93\u5165#\uFF09",
          tag,
          (newTag) => {
            if (newTag && newTag.trim() && newTag.trim() !== tag) {
              this.tags[i] = newTag.trim();
              this.renderTags();
            }
          }
        ).open();
      });
      const deleteBtn = tagItem.createEl("button", { cls: "jhua-tag-delete-btn", text: "\xD7" });
      deleteBtn.addEventListener("click", () => {
        this.tags.splice(i, 1);
        this.renderTags();
      });
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var AddTodoModal = class extends import_obsidian.Modal {
  constructor(app, todoManager, plugin, onSave) {
    super(app);
    this.content_text = "";
    this.priority = "medium";
    this.dueDate = "";
    this.tags = [];
    this.syncToDaily = true;
    this.app = app;
    this.todoManager = todoManager;
    this.plugin = plugin;
    this.onSave = onSave;
    this.dueDate = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("jhua-add-todo-modal");
    contentEl.createEl("h2", { text: "\u6DFB\u52A0\u5F85\u529E" });
    new import_obsidian.Setting(contentEl).setName("\u5F85\u529E\u5185\u5BB9").addText((text) => text.setPlaceholder("\u8F93\u5165\u5F85\u529E\u4E8B\u9879...").onChange((value) => this.content_text = value));
    new import_obsidian.Setting(contentEl).setName("\u4F18\u5148\u7EA7").addDropdown((dropdown) => dropdown.addOption("low", "\u4F4E").addOption("medium", "\u4E2D").addOption("high", "\u9AD8").setValue("medium").onChange((value) => this.priority = value));
    new import_obsidian.Setting(contentEl).setName("\u622A\u6B62\u65E5\u671F").setDesc("\u683C\u5F0F: YYYY-MM-DD\uFF0C\u9ED8\u8BA4\u4E3A\u4ECA\u5929").addText((text) => text.setValue(this.dueDate).onChange((value) => this.dueDate = value));
    new import_obsidian.Setting(contentEl).setName("\u6807\u7B7E").setDesc("\u7528\u9017\u53F7\u5206\u9694\u591A\u4E2A\u6807\u7B7E\uFF0C\u5982: \u5DE5\u4F5C,\u91CD\u8981").addText((text) => text.setPlaceholder("\u6807\u7B7E1, \u6807\u7B7E2").onChange((value) => {
      this.tags = value.split(",").map((t) => t.trim()).filter((t) => t);
    }));
    new import_obsidian.Setting(contentEl).setName("\u540C\u6B65\u5230\u65E5\u8BB0").setDesc("\u5C06\u5F85\u529E\u540C\u6B65\u5230\u5BF9\u5E94\u65E5\u671F\u7684\u65E5\u8BB0\u6587\u4EF6\u4E2D").addToggle((toggle) => toggle.setValue(this.syncToDaily).onChange((value) => this.syncToDaily = value));
    new import_obsidian.Setting(contentEl).addButton((button) => button.setButtonText("\u6DFB\u52A0").setCta().onClick(async () => {
      if (!this.content_text.trim()) {
        new import_obsidian.Notice("\u8BF7\u8F93\u5165\u5F85\u529E\u5185\u5BB9");
        return;
      }
      await this.todoManager.addTodo(
        this.content_text,
        this.priority,
        this.dueDate || void 0,
        this.tags.length > 0 ? this.tags : void 0
      );
      if (this.syncToDaily && this.dueDate) {
        await this.syncTodoToDailyNote(this.dueDate, this.content_text, false);
      }
      new import_obsidian.Notice("\u6DFB\u52A0\u6210\u529F\uFF01");
      this.onSave();
      this.close();
    }));
  }
  async syncTodoToDailyNote(dateStr, content, completed) {
    const dailyNotePath = this.getDailyNotePath(dateStr);
    try {
      let file = this.app.vault.getAbstractFileByPath(dailyNotePath);
      if (!(file instanceof import_obsidian.TFile)) {
        await this.createDailyNote(dateStr);
        file = this.app.vault.getAbstractFileByPath(dailyNotePath);
      }
      if (file instanceof import_obsidian.TFile) {
        let fileContent = await this.app.vault.read(file);
        const tasksRegex = /(#[📖\s]*Tasks\s*\n)/;
        const checkbox = completed ? "- [x]" : "- [ ]";
        const newTodoLine = `${checkbox} ${content}
`;
        if (tasksRegex.test(fileContent)) {
          fileContent = fileContent.replace(tasksRegex, `$1${newTodoLine}`);
        } else {
          fileContent += `
# \u{1F4D6}Tasks
${newTodoLine}`;
        }
        await this.app.vault.modify(file, fileContent);
      }
    } catch (e) {
      console.error("\u540C\u6B65\u5F85\u529E\u5230\u65E5\u8BB0\u5931\u8D25:", e);
    }
  }
  getDailyNotePath(dateStr) {
    const [year, month] = dateStr.split("-");
    return `01-\u9886\u57DF\uFF08Areas\uFF09/00-\u65E5\u5E38\u8BB0\u5F55/02-\u65E5\u8BB0/${year}/${year}-${month}/${dateStr}.md`;
  }
  async createDailyNote(dateStr) {
    const [year, month] = dateStr.split("-");
    const dirPath = `01-\u9886\u57DF\uFF08Areas\uFF09/00-\u65E5\u5E38\u8BB0\u5F55/02-\u65E5\u8BB0/${year}/${year}-${month}`;
    if (!this.app.vault.getAbstractFileByPath(dirPath)) {
      await this.app.vault.createFolder(dirPath);
    }
    const templatePath = this.plugin.settings.dailyNoteTemplate;
    const templateFile = this.app.vault.getAbstractFileByPath(templatePath);
    let initialContent = `---
tags:
  - daily_note
---
# \u{1F6A6}Tracking


# \u{1F4D2}Dairy


# \u{1F4D6}Tasks


# \u{1F396}\uFE0FDone \u5B8C\u6210\u7684\u4E8B\uFF01
`;
    if (templateFile instanceof import_obsidian.TFile) {
      initialContent = await this.app.vault.read(templateFile);
      initialContent = initialContent.replace(/<%\*[\s\S]*?%>/g, "");
    }
    const filePath = `${dirPath}/${dateStr}.md`;
    await this.app.vault.create(filePath, initialContent);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var NavigationSettingsModal = class extends import_obsidian.Modal {
  constructor(app, plugin, onCloseCallback = () => {
  }) {
    super(app);
    this.plugin = plugin;
    this.onCloseCallback = onCloseCallback;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("jhua-nav-settings-modal");
    contentEl.createEl("h2", { text: "\u5BFC\u822A\u8BBE\u7F6E" });
    new import_obsidian.Setting(contentEl).setName("\u6DFB\u52A0\u65B0\u5206\u7C7B").addButton((button) => button.setButtonText("+ \u6DFB\u52A0\u5206\u7C7B").setCta().onClick(() => {
      new CategoryEditModal(this.app, this.plugin, null, () => {
        this.onOpen();
      }).open();
    }));
    for (const category of this.plugin.settings.categories) {
      const categorySection = contentEl.createDiv({ cls: "jhua-category-section" });
      const categoryHeader = categorySection.createDiv({ cls: "jhua-category-header" });
      categoryHeader.createEl("span", { text: `${category.icon} ${category.name}`, cls: "jhua-category-title" });
      const categoryActions = categoryHeader.createDiv({ cls: "jhua-category-actions" });
      categoryActions.createEl("button", { text: "\u7F16\u8F91", cls: "jhua-btn-small" }).addEventListener("click", () => {
        new CategoryEditModal(this.app, this.plugin, category, () => {
          this.onOpen();
        }).open();
      });
      categoryActions.createEl("button", { text: "\u5220\u9664", cls: "jhua-btn-small jhua-btn-danger" }).addEventListener("click", async () => {
        if (confirm(`\u786E\u5B9A\u5220\u9664\u5206\u7C7B"${category.name}"\uFF1F`)) {
          this.plugin.settings.categories = this.plugin.settings.categories.filter((c) => c.id !== category.id);
          await this.plugin.saveSettings();
          this.onOpen();
        }
      });
      const itemsList = categorySection.createDiv({ cls: "jhua-items-list" });
      for (const item of category.items) {
        const itemRow = itemsList.createDiv({ cls: "jhua-item-row" });
        itemRow.createEl("span", { text: `${item.icon} ${item.name}` });
        itemRow.createEl("span", { text: item.path, cls: "jhua-item-path" });
        const itemActions = itemRow.createDiv({ cls: "jhua-item-actions" });
        itemActions.createEl("button", { text: "\u7F16\u8F91", cls: "jhua-btn-small" }).addEventListener("click", () => {
          new ItemEditModal(this.app, this.plugin, category.id, item, () => {
            this.onOpen();
          }).open();
        });
        itemActions.createEl("button", { text: "\u5220\u9664", cls: "jhua-btn-small jhua-btn-danger" }).addEventListener("click", async () => {
          if (confirm(`\u786E\u5B9A\u5220\u9664"${item.name}"\uFF1F`)) {
            category.items = category.items.filter((i) => i.id !== item.id);
            await this.plugin.saveSettings();
            this.onOpen();
          }
        });
      }
      const addItemBtn = categorySection.createEl("button", {
        text: "+ \u6DFB\u52A0\u5BFC\u822A\u9879",
        cls: "jhua-add-item-btn"
      });
      addItemBtn.addEventListener("click", () => {
        new ItemEditModal(this.app, this.plugin, category.id, null, () => {
          this.onOpen();
        }).open();
      });
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    this.onCloseCallback();
  }
};
var CategoryEditModal = class extends import_obsidian.Modal {
  constructor(app, plugin, category, onSave) {
    super(app);
    this.name = "";
    this.icon = "\u{1F4C1}";
    this.color = "#5B93D5";
    this.plugin = plugin;
    this.category = category;
    this.onSave = onSave;
    if (category) {
      this.name = category.name;
      this.icon = category.icon;
      this.color = category.color;
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: this.category ? "\u7F16\u8F91\u5206\u7C7B" : "\u6DFB\u52A0\u5206\u7C7B" });
    new import_obsidian.Setting(contentEl).setName("\u5206\u7C7B\u540D\u79F0").addText((text) => text.setPlaceholder("\u4F8B\u5982\uFF1A\u5DE5\u4F5C").setValue(this.name).onChange((value) => {
      this.name = value;
    }));
    new import_obsidian.Setting(contentEl).setName("\u56FE\u6807").setDesc("\u4F7F\u7528emoji\u56FE\u6807").addText((text) => text.setValue(this.icon).onChange((value) => {
      this.icon = value;
    }));
    new import_obsidian.Setting(contentEl).setName("\u989C\u8272").addColorPicker((picker) => picker.setValue(this.color).onChange((value) => {
      this.color = value;
    }));
    new import_obsidian.Setting(contentEl).addButton((button) => button.setButtonText("\u4FDD\u5B58").setCta().onClick(async () => {
      if (!this.name) {
        new import_obsidian.Notice("\u8BF7\u8F93\u5165\u5206\u7C7B\u540D\u79F0");
        return;
      }
      if (this.category) {
        this.category.name = this.name;
        this.category.icon = this.icon;
        this.category.color = this.color;
      } else {
        const newCategory = {
          id: `cat-${Date.now()}`,
          name: this.name,
          icon: this.icon,
          color: this.color,
          items: []
        };
        this.plugin.settings.categories.push(newCategory);
      }
      await this.plugin.saveSettings();
      new import_obsidian.Notice("\u4FDD\u5B58\u6210\u529F\uFF01");
      this.onSave();
      this.close();
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ItemEditModal = class extends import_obsidian.Modal {
  constructor(app, plugin, categoryId, item, onSave) {
    super(app);
    this.name = "";
    this.path = "";
    this.icon = "\u{1F4C4}";
    this.plugin = plugin;
    this.categoryId = categoryId;
    this.item = item;
    this.onSave = onSave;
    if (item) {
      this.name = item.name;
      this.path = item.path;
      this.icon = item.icon;
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: this.item ? "\u7F16\u8F91\u5BFC\u822A\u9879" : "\u6DFB\u52A0\u5BFC\u822A\u9879" });
    new import_obsidian.Setting(contentEl).setName("\u540D\u79F0").addText((text) => text.setPlaceholder("\u4F8B\u5982\uFF1A\u5DE5\u4F5C\u7B14\u8BB0").setValue(this.name).onChange((value) => {
      this.name = value;
    }));
    new import_obsidian.Setting(contentEl).setName("\u8DEF\u5F84").setDesc("\u7B14\u8BB0\u8DEF\u5F84\u6216AdvancedURI\uFF08obsidian://...\uFF09").addText((text) => text.setPlaceholder("\u6587\u4EF6\u5939/\u7B14\u8BB0\u540D \u6216 obsidian://...").setValue(this.path).onChange((value) => {
      this.path = value;
    }));
    new import_obsidian.Setting(contentEl).setName("\u56FE\u6807").setDesc("\u4F7F\u7528emoji\u56FE\u6807").addText((text) => text.setValue(this.icon).onChange((value) => {
      this.icon = value;
    }));
    new import_obsidian.Setting(contentEl).addButton((button) => button.setButtonText("\u4FDD\u5B58").setCta().onClick(async () => {
      if (!this.name || !this.path) {
        new import_obsidian.Notice("\u8BF7\u8F93\u5165\u540D\u79F0\u548C\u8DEF\u5F84");
        return;
      }
      const category = this.plugin.settings.categories.find((c) => c.id === this.categoryId);
      if (!category) {
        new import_obsidian.Notice("\u5206\u7C7B\u4E0D\u5B58\u5728");
        return;
      }
      if (this.item) {
        this.item.name = this.name;
        this.item.path = this.path;
        this.item.icon = this.icon;
      } else {
        const newItem = {
          id: `item-${Date.now()}`,
          name: this.name,
          path: this.path,
          icon: this.icon
        };
        category.items.push(newItem);
      }
      await this.plugin.saveSettings();
      new import_obsidian.Notice("\u4FDD\u5B58\u6210\u529F\uFF01");
      this.onSave();
      this.close();
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var BannerSettingsModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("jhua-banner-settings-modal");
    contentEl.createEl("h2", { text: "Banner\u8BBE\u7F6E" });
    new import_obsidian.Setting(contentEl).setName("\u80CC\u666F\u56FE\u7247\u8DEF\u5F84").setDesc("Banner\u7684\u80CC\u666F\u56FE\u7247\uFF0C\u652F\u6301png/jpg/webp").addText((text) => text.setPlaceholder("VaultSources/pasted_pics/xxx.png").setValue(this.plugin.settings.bannerImage).onChange(async (value) => {
      this.plugin.settings.bannerImage = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(contentEl).setName("\u6B22\u8FCE\u8BED").setDesc("Banner\u663E\u793A\u7684\u6B22\u8FCE\u6587\u5B57").addText((text) => text.setPlaceholder("\u6B22\u8FCE\u56DE\u6765").setValue(this.plugin.settings.bannerTitle).onChange(async (value) => {
      this.plugin.settings.bannerTitle = value;
      await this.plugin.saveSettings();
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var JhuaHPageSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Jhua\u4E3B\u9875\u63D2\u4EF6\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u5F85\u529E\u7F13\u5B58\u8DEF\u5F84").setDesc("\u5F85\u529E\u4E8B\u9879JSON\u7F13\u5B58\u6587\u4EF6\u7684\u5B58\u50A8\u8DEF\u5F84").addText((text) => text.setPlaceholder("VaultSources/\u4E3B\u9875\u6570\u636E/todos.json").setValue(this.plugin.settings.todoCachePath).onChange(async (value) => {
      this.plugin.settings.todoCachePath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Banner\u80CC\u666F\u56FE").setDesc("Banner\u533A\u57DF\u7684\u80CC\u666F\u56FE\u7247\u8DEF\u5F84").addText((text) => text.setPlaceholder("VaultSources/pasted_pics/xxx.png").setValue(this.plugin.settings.bannerImage).onChange(async (value) => {
      this.plugin.settings.bannerImage = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Banner\u6807\u9898").setDesc("Banner\u533A\u57DF\u663E\u793A\u7684\u6B22\u8FCE\u8BED").addText((text) => text.setPlaceholder("\u6B22\u8FCE\u56DE\u6765").setValue(this.plugin.settings.bannerTitle).onChange(async (value) => {
      this.plugin.settings.bannerTitle = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u65E5\u8BB0\u6A21\u677F\u8DEF\u5F84").setDesc("\u521B\u5EFA\u65E5\u8BB0\u65F6\u4F7F\u7528\u7684\u6A21\u677F\u6587\u4EF6\u8DEF\u5F84").addText((text) => text.setPlaceholder("templates/11-\u65E5\u8BB0\u6A21\u677F.md").setValue(this.plugin.settings.dailyNoteTemplate).onChange(async (value) => {
      this.plugin.settings.dailyNoteTemplate = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u9879\u76EE\u8DDF\u8E2A\u521B\u5EFAURI").setDesc("\u9879\u76EE\u8DDF\u8E2A\u533A\u57DF\u521B\u5EFA\u6309\u94AE\u7684AdvancedURI").addText((text) => text.setPlaceholder("obsidian://adv-uri?vault=...").setValue(this.plugin.settings.projectCreateUri).onChange(async (value) => {
      this.plugin.settings.projectCreateUri = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u5F85\u6574\u7406\u521B\u5EFAURI").setDesc("\u5F85\u6574\u7406\u533A\u57DF\u521B\u5EFA\u6309\u94AE\u7684AdvancedURI").addText((text) => text.setPlaceholder("obsidian://adv-uri?vault=...").setValue(this.plugin.settings.unorganizedCreateUri).onChange(async (value) => {
      this.plugin.settings.unorganizedCreateUri = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u5BFC\u822A\u8BBE\u7F6E").setDesc("\u914D\u7F6E\u5BFC\u822A\u5206\u7C7B\u548C\u9879\u76EE").addButton((button) => button.setButtonText("\u6253\u5F00\u5BFC\u822A\u8BBE\u7F6E").onClick(() => {
      new NavigationSettingsModal(this.app, this.plugin).open();
    }));
  }
};
var JhuaHPagePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_HOMEPAGE, (leaf) => new HomepageView(leaf, this));
    this.addRibbonIcon("home", "\u6253\u5F00\u4E3B\u9875", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-homepage",
      name: "\u6253\u5F00\u4E3B\u9875",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new JhuaHPageSettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_HOMEPAGE);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_HOMEPAGE);
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.setViewState({
      type: VIEW_TYPE_HOMEPAGE,
      active: true
    });
    this.app.workspace.revealLeaf(leaf);
  }
};
